apiVersion: apps/v1
kind: Deployment
metadata:
  name: copy-myapp
spec:
  selector:
    matchLabels:
      app: copy-myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: copy-myapp
    spec:
      containers:
      - name: copy-myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
