apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker pull nginxinc/nginx-unprivileged:stable-alpine
        name: nginx-container
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
        ports:
          - containerPort: 80
